version: "3.9"
services:

  redis:
    volumes:
        - ./db/redis:/data
    image: redis:7-alpine
    ports:
      - 6379:6379
    networks:
      - network

  parser:
    build: .
    command: python main.py
    volumes:
      - ./parser:/code/
    depends_on:
      - redis
    networks:
      - network

networks:
  network:
    driver: bridge